GET http://localhost:3000

### non existent route
GET http://localhost:3000/abc_xyz

### auth route

#### login
POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "23456wertg"
}


#### register
POST http://localhost:3000/api/auth/register 
Content-Type: application/json

{
  "email": "test7@gmail.com",
  "password": "23456wertg",
  "confirm_password": "23456wertg"
}

### add track
PUT http://localhost:3000/api/auth/favourites/7h1YqA5MZrRxmkUFpukRcp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDE4MTI5NDMsImV4cCI6MTcwMTg0ODk0MywiYXVkIjpbIjY1NjkxYjExY2EyYTViMDE0Mjg3N2I0MiJdLCJpc3MiOiJwaWNrdXJwYWdlLmNvbSJ9.4t6fa8RGe_llmxHiMCGYhUGg2PPu89Q4LTng8FJl3V8
Content-Type: application/json

#### jwt refresh-token
POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDAzMjQ2NDgsImV4cCI6MTczMTg4MjI0OCwiYXVkIjpbIjY1NTZjYTc0YzJjMWY1NDkxZDU0MzBjYyJdLCJpc3MiOiJwaWNrdXJwYWdlLmNvbSJ9.oHwu6FxL4uWT5RVpyLTtPpMrwr0DlWT3AY6-SE1ZpmE"
}

### get all favourites
GET http://localhost:3000/api/auth/favourites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDE4MTI5NDMsImV4cCI6MTcwMTg0ODk0MywiYXVkIjpbIjY1NjkxYjExY2EyYTViMDE0Mjg3N2I0MiJdLCJpc3MiOiJwaWNrdXJwYWdlLmNvbSJ9.4t6fa8RGe_llmxHiMCGYhUGg2PPu89Q4LTng8FJl3V8


### remove a track from favourites
DELETE http://localhost:3000/api/auth/favourites/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDE4MTI5NDMsImV4cCI6MTcwMTg0ODk0MywiYXVkIjpbIjY1NjkxYjExY2EyYTViMDE0Mjg3N2I0MiJdLCJpc3MiOiJwaWNrdXJwYWdlLmNvbSJ9.4t6fa8RGe_llmxHiMCGYhUGg2PPu89Q4LTng8FJl3V8


#### logout
DELETE http://localhost:3000/api/auth/logout 
content-type: application/json

{
"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDE4MTE0MjQsImV4cCI6MTczMzM2OTAyNCwiYXVkIjpbIjY1NjkxYjExY2EyYTViMDE0Mjg3N2I0MiJdLCJpc3MiOiJwaWNrdXJwYWdlLmNvbSJ9.ZRu1p1-6wYkpq_p3n17TRPyom32Mb98wWF13WUrofDQ"
}